export const objectPerson = {
  persontype: "",
  firstname: "",
  lastname: "",
  gender: "",
  birthdate: new Date(),
  nationalid: "",
  idtype: "",
  maritalstatus: "",
  marriagedt: new Date(),
  address: {
    address1: "",
    address2: "",
    city: "",
    state: "",
    country: "",
    postalcode: "",
    phone1: "",
    phone2: "",
    phone3: "",
    email: "",
  },
  education: {
    degree: "",
    degreetype: "",
    completiondate: new Date(),
    school: "",
  },
  employment: {
    employername: "",
    position: "",
    startdate: "",
    enddate: "",
    iscurrent: true,
    compensation: 0,
  },
  profileimage: "anu_profile.jpg",
};
